var columns = {
searchTerms: {
        'keywordID': {
            type: 'uniq', // string, number, date, money, precent,uniq --LaterOn: custom, 
            name: 'keywordID',
            display: 'keywordID',
            actions: ['addKeywork', 'removeKeyword'],
            filters: ['equal', 'notContains', 'value', 'duplicates'],
            isSortable: false,
            isVisible: false,
            isEdit : false,
            isFilter: false,
            isActive: true,
            width: '100px',
        },
        'adGroup': {
            type: 'string',
            name: 'adGroup',
            display: 'adGroup',
            actions: [],
            filters: ['begins', 'value'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true,
            isFilter: true,
            isActive: true,
            width: '108px',
        },
        'searchTerm': {
            type: 'string',
            name: 'searchTerm',
            display: 'search term',
            actions: [],
            filters: ['equal', 'notContains', 'value', 'duplicates','begins'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true,
            isFilter: true,
            isActive: true,
            width: '155px',
        },
        'impressions': {
            type: 'number',
            name: 'impressions',
            display: 'impressions',
            actions: [],
            filters: ['equal', 'notContains', 'value', 'duplicates'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true,
            isFilter: true,
            isActive: true,
            width: '107px',
        },
        'clicks': {
            type: 'number',
            name: 'clicks',
            display: 'clicks',
            actions: [],
            filters: ['equal', 'notContains', 'value', 'duplicates'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true,
            isFilter: true,
            isActive: true,
            width: '100px',
        },
        'avgPosition': {
            type: 'number',
            name: 'avgPosition',
            display: 'avg Position',
            actions: [],
            filters: ['equal', 'notContains', 'value', 'duplicates'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true,
            isFilter: true,
            isActive: true,
            width: '106px',
        },
        'conversions': {
            type: 'number',
            name: 'conversions',
            display: 'conversions',
            actions: [],
            filters: ['equal', 'notContains', 'value', 'duplicates'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true, 
            isFilter: true,
            isActive: true,
            width: '100px',
        },
        'costConv': {
            type: 'number',
            name: 'costConv',
            display: 'cost',
            actions: [],
            filters: ['equal', 'notContains', 'value', 'duplicates'],
            actionList: [],
            isSortable: true,
            isVisible: true,
            isEdit : true, 
            isFilter: true,
            isActive: true,
            width: '100px',
        }
    }
};

var columnsManager = {
    getColumns: function (type) {
        return columns[type];
    }
}

module.exports = columnsManager;